replicaCount: 2
image:
  tag: quay-quay-enterprise.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-tekton-typ-fruit:1.0.2-main # written by ploigos-step-runner
route:
  hostname: fruit-std-workflow-tekton.prod.apps.tssc.rht-set.com
